/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ExtIf_constants.h"

namespace ext_iface {

const ExtIfConstants g_ExtIf_constants;

ExtIfConstants::ExtIfConstants() {
}

} // namespace

