/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ExtIf_CONSTANTS_H
#define ExtIf_CONSTANTS_H

#include "ExtIf_types.h"

namespace ext_iface {

class ExtIfConstants {
 public:
  ExtIfConstants();

};

extern const ExtIfConstants g_ExtIf_constants;

} // namespace

#endif
